baseURL: 'https://makenziebird.com/'
languageCode: 'en-us'
title: 'Makenzie Bird'
theme: 'PaperMod'
outputs:
  home:
    - html
    - rss
    - json
menu:
  main:
    - identifier: articles
      name: Articles
      url: /articles/
      weight: 10
    - identifier: poems
      name: Poems
      url: /poems/
      weight: 20
    - identifier: stories
      name: Stories
      url: /stories/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40
params:
    homeInfoParams:
        Title: Welcome
        Content: You can read my [articles](/articles), [poems](/poems), and [stories](/stories). Or feel free to browse the [archives](/archives) by [tags](/tags) or [category](/categories).
    ShowFullTextinRSS: true
    fuseOpts: # search settings
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 2
        keys: ["title", "permalink", "summary", "content"]
