baseURL: 'https://makenziebird.com/'
languageCode: 'en-us'
title: 'Makenzie Bird'
theme: 'PaperMod'
outputs:
  home:
    - html
    - rss
    - json
menu:
  main:
    - identifier: articles
      name: Articles
      url: /articles/
      weight: 10
    - identifier: fragments
      name: Fragments
      url: /fragments/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: search
      pre: <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"></circle><line x1="28" y1="28" x2="16.65" y2="16.65"></line></svg>
      name:
      url: /search/
      weight: 40
params:
    homeInfoParams:
        Title: Hello!
        Content: "What one has not experienced, one will never understand in print." –Isadora Duncan
        You can check out full posts in [articles](/articles) or shorter pieces, [fragments](/fragments).
    ShowFullTextinRSS: true
    fuseOpts: # search settings
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 2
        keys: ["title", "permalink", "summary", "content"]
        
