baseURL: 'https://makenziebird.com/'
languageCode: 'en-us'
title: 'Makenzie Bird'
theme: 'PaperMod'
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: articles
      name: Articles
      url: /articles/
      weight: 10
    - identifier: poems
      name: Poems
      url: /poems/
      weight: 20
    - identifier: stories
      name: Stories
      url: /stories/
      weight: 30
    - identifier: search
      name: Search
      pre: <i class='fa fa-search'></i>
      url: /search/
      weight: 40
params:
    fuseOpts: # search settings
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 2
        keys: ["title", "permalink", "summary", "content"]
